name: Calculator_static_check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  codacy-analysis-cli:
    name: Codacy Static Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
