name: Calculator
on:
  push:
    branches: [ "main" ]
    
env:
  MAJOR_NUM: '1'
  MINOR_NUM: '0'
  PATCH_NUM: ${{ github.run_number }}
  
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports



  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: docker build --build-arg PATCH_NUM=$PATCH_NUM --build-arg MAJOR_NUM=$MAJOR_NUM --build-arg MINOR_NUM=$MINOR_NUM -t calculator .

      - name: Run ls
        run: ls
        
      - name: show_image
        run: docker images
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_U }}
          password: ${{ secrets.DOCKER_HUB_T }}    
          
      - name: tag latest
        run: docker tag calculator:latest vova0911/calculator:latest
          
      - name: push latest
        run: docker push vova0911/calculator:latest
