name: Calculator

on:
  push:
    branches: [ "main" ]
    

    
env:
  MAJOR_NUM: '1'
  MINOR_NUM: '0'
  PATCH_NUM: ${{ github.run_number }}
  

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
  
jobs: #https://github.com/marketplace/actions/dependency-check    
  Dockerfile_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: '.'
          framework: dockerfile 
          
          
  Dep_check_test:
    needs: Dockerfile_scan
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

  build:
    needs: Dep_check_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: docker build --build-arg PATCH_NUM=$PATCH_NUM --build-arg MAJOR_NUM=$MAJOR_NUM --build-arg MINOR_NUM=$MINOR_NUM -t vova0911/calculator:latest .
        
      - name: Run ls
        run: ls
        
      - name: Run im
        run: docker images
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_U }}
          password: ${{ secrets.DOCKER_HUB_T }}  
          
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
          
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
            
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key vova0911/calculator:latest -y
                 
      - name: push latest
        run: docker push vova0911/calculator:latest

      - name: Write public signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
          
      - name: Verify Image
        run: cosign verify --key cosign.key vova0911/calculator:latest
        


