name: Calculator

on:
  push:
    branches: [ "main" ]
    

    
env:
  MAJOR_NUM: '1'
  MINOR_NUM: '0'
  PATCH_NUM: ${{ github.run_number }}
  
jobs: #https://github.com/marketplace/actions/dependency-check    
  Dockerfile_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: '.'
          framework: dockerfile 
          

  dependancy-scan:
    needs: Dockerfile_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Build with Maven
        run: mvn clean install

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Calculator'
          path: '.'
          format: 'SARIF'
          out: 'reports'
          args: >
            --failOnCVSS 10
            --enableRetired
            

  build:
    needs: dependancy-scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: docker build --build-arg PATCH_NUM=$PATCH_NUM --build-arg MAJOR_NUM=$MAJOR_NUM --build-arg MINOR_NUM=$MINOR_NUM -t vova0911/calculator:latest .
        
      - name: Run ls
        run: ls
        
      - name: Run im
        run: docker images
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_U }}
          password: ${{ secrets.DOCKER_HUB_T }}  
                 
      - name: push latest
        run: docker push vova0911/calculator:latest
        
          
  sign-image: #https://dev.to/n3wt0n/sign-your-container-images-with-cosign-github-actions-and-github-container-registry-3mni
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_U }}
          password: ${{ secrets.DOCKER_HUB_T }} 
      
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
          
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
            
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key vova0911/calculator:latest -y
           
             
  verify-image:
    runs-on: ubuntu-latest
    needs: sign-image
    steps:
      - uses: actions/checkout@v3
      
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
          
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
    
      - name: Verify Image
        run: cosign verify --key cosign.key vova0911/calculator:latest
        
