name: Calculator
on:
  push:
    branches: [ "main" ]
    
env:
  MAJOR_NUM: '1'
  MINOR_NUM: '0'
  PATCH_NUM: ${{ github.run_number }}
  
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: docker build --build-arg PATCH_NUM=$PATCH_NUM --build-arg MAJOR_NUM=$MAJOR_NUM --build-arg MINOR_NUM=$MINOR_NUM -t calculator .

      - name: Run ls
        run: ls
        
      - name: show_image
        run: docker images
        
	  - name: Login to Docker Hub
        uses: docker/login-action@v3
          username: ${{ secrets.DOCKER_HUB_U }}
          password: ${{ secrets.DOCKER_HUB_T }}
